image:
  name: 097427577457.dkr.ecr.ap-south-1.amazonaws.com/pipeline8:latest
  aws:
    access-key: $AWS_ACCESS_KEY_ID
    secret-key: $AWS_SECRET_ACCESS_KEY

definitions:
  caches:
    vendor: vendor

setup: &setup
  name: CI
  script:
    - composer install
    - ./vendor/bin/grumphp run
  caches:
    - vendor
    - composer

pipelines:
  default:
    - step: *setup

  branches:
    master:
      - step: *setup
    production:
      - step: *setup
    development:
      - step: *setup
    staging:
      - step: *setup
    testing:
      - step: *setup
